### ISSUE TITLE
Precisions on MetaDataGraphs

### ISSUE THREAD

**Issue by gdalle** [UniStuttgart-IKR/AttributeGraphs.jl#4]
Hi, it's me again ^^

Just to say that MetaDataGraphs is not maintained. I think the profusion of different standards is not helpful, so what I would like to do is to give that package name to what is currently called MetaGraphsNext. Thoughts?

**Comment by filchristou** [comment]
So you would like to rename MetaGraphsNext to MetaDataGraphs ? Is there a related issue on the MetaGraphsNext repo ?
I generally do think that that the name "MetaGraphsNext" could be better for a library that ambitions to lead the MetaGraphs regime in julia. However, I would be more concerned on building the infastructure for this rather the naming right now :P 
Changing the name could be a 1.0.0 change.

**Comment by gdalle** [comment]
I think we discussed it on Slack briefly but of course Slack has since swallowed it. It's not a pressing matter by any stretch, my thought process was that graph beginners might be scared to use something that's called "MetaGraphsNext" for two reasons:

1. What is "Meta" exactly? It's the data but how would they know
2. The "Next" prefix is useless for anyone unfamiliar with the package history, and may make it seem more complex

**Comment by filchristou** [comment]
I agree. But I think such discussions are better made in the MetaGraphsNext.jl repo. I opened an issue there https://github.com/JuliaGraphs/MetaGraphsNext.jl/issues/58 and I close this one.
