### ISSUE TITLE
Typo: missing an "r"

### ISSUE THREAD

**Issue by gdalle** [UniStuttgart-IKR/AttributeGraphs.jl#6]
https://github.com/UniStuttgart-IKR/AttributeGraphs.jl/blob/0c548f177ed02e6d671fcfedf978961bd414b088/src/abstractattributegraph.jl#LL1C15-L1C36

**Comment by filchristou** [comment]
Closed by https://github.com/UniStuttgart-IKR/AttributeGraphs.jl/commit/6cb492a1c36c66c097009b9a83783b4604e1fa70
